version: '3.9'

services:
  fpl:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    container_name: fpl
    image: fpl:latest
    ports:
      - 3000:3000
      - 8000:8000